name: flutter_master
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.1

  # Functional Extensions & Methods
  dartz: ^0.10.1

  # Networking

  # Networking
  api:
    path: ./api
  dio: ^5.1.2
  freezed_annotation: 2.2.0
  json_annotation: 4.8.1
  retrofit: 4.0.1

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.1

  # Local Storage
  secure_shared_preferences: ^0.0.4

  # Routing
  auto_route: 7.8.3
  # firebase_core: ^2.21.0
  # device_preview: ^1.1.0
  flutter_svg: ^2.0.8
  gap: ^3.0.1
  google_fonts: ^5.1.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.1
  # firebase_messaging: ^14.7.3
  change_app_package_name: ^1.1.0
  # flutter_local_notifications: ^16.1.0
  file_picker: ^6.1.1
  camera: ^0.10.5+9
  objectbox: ^2.3.1
  objectbox_flutter_libs: 2.3.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6

  flutter_gen_runner: 5.3.2
  retrofit_generator: ^7.0.1
  riverpod_generator: ^2.2.3
  json_serializable: 6.7.1
  freezed: 2.3.4
  custom_lint: 0.4.0
  # riverpod_lint: 1.3.2
  auto_route_generator: 7.1.1
  flutter_launcher_icons: ^0.13.1
  objectbox_generator: 2.3.1

flutter_icons:
  image_path: 'assets/icons/logo.png'
  android: 'launcher_icon'
  ios: true
  # android: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icons/
    - assets/json/
    - assets/images/

flutter_gen:
  output: lib/presentation/shared/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
